character_name= input("Enter a character name:")
character_age= input("Enter age:")
character_place= input("Enter place:")
character_brain= input("Enter a brain quality(like POWERFUL , SLOW):")
character_group= input("Enter a group name:")
print(" There was a person named " + character_name +  " in a small town " + ",")
print(" named " + character_place + " in USA " ",")
print(" He was " + character_age + " years old " + " and very smart.")
print(" his brain quality is " + character_brain + " and strong " + ",")
print(" and he belongs to " + character_group + " group. ")
print("people in this " + character_group + " are smart and energetic.")